/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "timer_encoder_mode_integration_test.h"
#include "timer_basic_timebase_integration_test.h"
#include "gpio_integration_test.h"
#include "spi_integration_test.h"
#include "i2c_integration_test.h"
#include "usart_integration_test.h"
#include "SPIDriver.h"
#include "timers_integration_test.h"
#include "dma_integration_test.h"
#include "floating_point_utils.h"
#include "stm32f7xx.h"
#include "TIMER_Driver.h"
#include "timer_input_capture_integration_test.h"
#include "flash_operations_integration_tests.h"


int main(void)
{
	setup_gpio_integration_test_gpio_portB();
	//setup_basic_timebase_integration_test_no_interrupts();
	//setup_basic_timebase_integration_test_interrupt_enabled();
	//setup_timers_integration_test();
	//setup_input_capture();
	//setup_dma_integration_test();
	//setup_usart_integration_test();
	//setup_timer_encoder_mode_integration_test();
	setup_flash_device();
	//timer3 = getEncoderTimer();
	//setup_i2c_master_integration_test();
	//test_BMP180_Chip_ID_Read();
	//test_BMP180_Ctrl_Measurement_Read();
	//setup_spi_master_integration_test(SPI_MODE_THREE);
	//test_CMD_Arduino_Slave_LED_CTRL();
	//test_tx_only_Arduino_Slave();
	//	test_get_ADXL345_Device_ID();
	//	test_set_ADXL345_BW_Rate_Registers();
	//	test_set_ADXL345_Power_CTL_Registers();
	//	test_read_ADXL345_Power_CTL_Registers();
	//dma_memory_transfer_test();
	//test_tx_send_long_string();
	//led_pwm_burst_operation();
	//turn_on_all_LEDs_PORTB();
	//test_tx_send_long_string_circular_mode();
	test_flash_erase_and_write();
	while (1) {
		//capture_tim5_channel_1();
		//polled_timer_test();
		//encoder_position_test();
		//encoder_direction_test();
		//test_tx_rx_basic_prompt();
		//led_pwm_brighted_dimming_test();
		//test_tx_send_long_string();
		//encoder_read_test();
		//delayUSART(2000);
		//led_pwm_burst_operation();
	}
}

void SystemInit (void) {
	SCB->VTOR = 0x08008000;
	enable_fpu_processor();
}

